version: "3.9"
services:
  api:
    restart: unless-stopped
    build:
      dockerfile: dockerfile.dev
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - .:/var/app
      - /var/api/node_modules
