name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update packages
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dcraw and libraw
        run: sudo apt-get install -y dcraw libraw-bin

      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"

      - name: "Install dependencies"
        run: npm i
        env:
          AUTHORIZED_API_KEYS: "
            apEB2LCKRFBfCT6aVfhv:
            name: GitHub API Key
            description: API KEY used during GitHub CI
            "

      - name: "Build API"
        run: npm run build
